on:
  push:
    branches:
      - master
  pull_request:

name: Check CMake install

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get latest CMake
      uses: lukka/get-cmake@latest

    - name: Install tatami
      run: |
        git clone https://github.com/tatami-inc/tatami dep-tatami --depth=1
        cd dep-tatami
        cmake -S . -B build -DTATAMI_TESTS=OFF
        sudo cmake --install build

    - name: Install eminem
      run: |
        git clone https://github.com/tatami-inc/eminem dep-eminem --depth=1
        cd dep-eminem
        cmake -S . -B build -DEMINEM_TESTS=OFF
        sudo cmake --install build

    - name: Configure the build
      run: cmake -S . -B build -DTATAMI_MTX_FETCH_EXTERN=OFF -DTATAMI_MTX_TESTS=OFF

    - name: Install the library
      run: sudo cmake --install build

    - name: Test downstream usage
      run: |
        mkdir _downstream
        touch _downstream/source.cpp
        cat << EOF > _downstream/CMakeLists.txt
        cmake_minimum_required(VERSION 3.24)
        project(test_install)
        add_executable(whee source.cpp)
        find_package(tatami_tatami_mtx)
        target_link_libraries(whee tatami::tatami_mtx)
        EOF
        cd _downstream && cmake -S . -B build
